services:

  mlflow:
    build: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_ENABLE_PROXY_FIX=true

  training:
    build: services/training
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./models:/models
    depends_on:
      - mlflow

  inference:
    build: services/inference
    ports:
      - "8001:8000"
    volumes:
      - ./models:/models
    depends_on:
      - training
