version: "3.9"

services:

  # =========================
  # API GATEWAY (ENTRYPOINT)
  # =========================
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      - PREDICT_API_URL=http://predict-api:8001
      - TRAIN_API_URL=http://training-api:8002
      - AUTH_API_URL=http://auth-api:8003
    depends_on:
      - predict-api
      - training-api
      - auth-api
    networks:
      - mlops_network

  # =========================
  # AUTH SERVICE
  # =========================
  auth-api:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: auth-api
    ports:
      - "8003:8003"
    networks:
      - mlops_network

  # =========================
  # PREDICTION SERVICE
  # =========================
  predict-api:
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    container_name: predict-api
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - mlops_network

  # =========================
  # TRAINING SERVICE
  # =========================
  training-api:
    build:
      context: .
      dockerfile: src/training/Dockerfile
    container_name: training-api
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - mlops_network
    environment:
     - MLFLOW_TRACKING_USERNAME=${DAGSHUB_USER}
     - MLFLOW_TRACKING_PASSWORD=${DAGSHUB_TOKEN}

  # =========================
  # AIRFLOW
  # =========================
  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    depends_on:
      - gateway
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - mlops_network

# =========================
# NETWORK
# =========================
networks:
  mlops_network:
    driver: bridge