services:
  
  gateway:
    container_name: gateway_AF
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - INFERENCE_URL=http://inference:8000
      - TRAINING_URL=http://training:8000
    depends_on:
      - inference
      - training
    networks:
      - mlops_network

  
  training:
    container_name: training_AF
    build:
      context: .
      dockerfile: src/training/Dockerfile
    ports:
      - "8002:8000" 
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./models:/app/models
    depends_on:
      - mlflow
    networks:
      - mlops_network


  inference:
    container_name: inference_AF
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    ports:
      - "8001:8000"  
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./models:/app/models
    networks:
      - mlops_network


  mlflow:
    container_name: mlflow_AF
    build:
      context: .
      dockerfile: src/mlflow/Dockerfile
    ports:
      - "5000:5000"
    volumes:
    
      - ./mlflow/mlruns:/mlflow/mlruns
    networks:
      - mlops_network

networks:
  mlops_network:
    driver: bridge
