# =========================
# BASE IMAGE
# =========================
FROM python:3.12-slim

# =========================
# WORKDIR
# =========================
WORKDIR /app

# =========================
# INSTALL DEPENDENCIES
# =========================
COPY gateway/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# =========================
# COPY CODE
# =========================
COPY gateway /app

# =========================
# PORT
# =========================
EXPOSE 8000

# =========================
# RUN APP
# =========================
CMD ["uvicorn", "gateway_main:app", "--host", "0.0.0.0", "--port", "8000"]